image: node:latest

install-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - npm install

test-job:
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 3 seconds"
    - echo "which simulates a test that runs 3 seconds longer than test-job1"
    - sleep 3

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
    - npm install
    - CI=false npm run build
    - npm publish
    - echo "-- publish completed succesfully"
  only:
    - main
